import {
  collection,
  doc,
  deleteDoc,
  getDoc,
  getDocs,
  onSnapshot,
  runTransaction,
  setDoc,
  writeBatch,
  type CollectionReference,
  type DocumentData,
  type Firestore,
} from 'firebase/firestore';
import type {
  ItineraryDay,
  ItineraryActivity,
  PinnedPoint,
  PendingPlace,
  ChatMessage,
  TripLogistics,
  CriticalEvent,
} from '../types';
import { mapCategoryToActivityType } from '../utils/category';
import { db as defaultDb } from '../lib/firebase';
import type { TripRepository, Unsubscribe } from './ports';

const EMPTY_LOGISTICS: TripLogistics = { drivers: [], vehicle: null };

const APPROVED_PLACE_PIN_IMAGE =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuC8kbbAVSGnOTZjuDOJbgKxvomdkFv5dlPjxQlL8K4RSkPMJynCQ4XkYX-8nN_ieyYhjFAimCZlGiwUXYJfrIfR8xfU4_5aR9W6jAP36Qtk_Tvi0IZaTtS6mGiabINpPHyHmdVY6G6smwzHqNZGww_PiqileoStp0VHXbxZzzHkQbhDpOLVxIelUlB_IhB4m6m-nTXBkqaE79Wyy9pcbbcQrfpTJ_iOzrVMtd_4wN1Wrnk1_kd2hXCvD1to7uznxceO9gusiK382DnK';

/**
 * Firestore adapter for `TripRepository` (spec "firestore-trip-data" domain:
 * zero behavior drift from `InMemoryTripRepository`, same port-method
 * signatures, verified by the shared `tripRepository.contract.ts` suite
 * against the local emulator). Firestore layout per design: one document per
 * `ItineraryDay` (nested `activities[]`), one document per pin/pending
 * place/chat message, all under `trips/{tripId}/...` subcollections, each
 * keyed by the entity's own `id` field (not an autogenerated Firestore id) so
 * mutation methods can address documents directly.
 *
 * Accepts an optional `Firestore` instance (defaulting to the app's shared
 * `db` from `src/lib/firebase.ts`) so tests can inject an emulator-connected
 * instance instead of hitting the real project.
 */
export class FirestoreTripRepository implements TripRepository {
  private readonly db: Firestore;

  constructor(firestoreDb: Firestore = defaultDb) {
    this.db = firestoreDb;
  }

  private itineraryDaysRef(tripId: string): CollectionReference<DocumentData> {
    return collection(this.db, 'trips', tripId, 'itineraryDays');
  }

  private pinsRef(tripId: string): CollectionReference<DocumentData> {
    return collection(this.db, 'trips', tripId, 'pins');
  }

  private pendingPlacesRef(tripId: string): CollectionReference<DocumentData> {
    return collection(this.db, 'trips', tripId, 'pendingPlaces');
  }

  private chatRef(tripId: string): CollectionReference<DocumentData> {
    return collection(this.db, 'trips', tripId, 'chat');
  }

  private criticalEventsRef(tripId: string): CollectionReference<DocumentData> {
    return collection(this.db, 'trips', tripId, 'criticalEvents');
  }

  private logisticsDocRef(tripId: string) {
    // Single doc under its own subcollection (same one-level-deep shape the
    // security rules' nested `match /{subcollection}/{docId}` already
    // covers, so no rules change is needed for this new seam).
    return doc(this.db, 'trips', tripId, 'logistics', 'main');
  }

  subscribeItinerary(tripId: string, cb: (days: ItineraryDay[]) => void): Unsubscribe {
    return onSnapshot(this.itineraryDaysRef(tripId), snapshot => {
      const days = snapshot.docs
        .map(d => d.data() as ItineraryDay)
        .sort((a, b) => a.dayNumber - b.dayNumber);
      cb(days);
    });
  }

  subscribePins(tripId: string, cb: (pins: PinnedPoint[]) => void): Unsubscribe {
    return onSnapshot(this.pinsRef(tripId), snapshot => {
      cb(snapshot.docs.map(d => d.data() as PinnedPoint));
    });
  }

  subscribePendingPlaces(tripId: string, cb: (places: PendingPlace[]) => void): Unsubscribe {
    return onSnapshot(this.pendingPlacesRef(tripId), snapshot => {
      cb(snapshot.docs.map(d => d.data() as PendingPlace));
    });
  }

  subscribeChat(tripId: string, cb: (messages: ChatMessage[]) => void): Unsubscribe {
    return onSnapshot(this.chatRef(tripId), snapshot => {
      cb(snapshot.docs.map(d => d.data() as ChatMessage));
    });
  }

  subscribeLogistics(tripId: string, cb: (logistics: TripLogistics) => void): Unsubscribe {
    return onSnapshot(this.logisticsDocRef(tripId), snapshot => {
      cb(snapshot.exists() ? (snapshot.data() as TripLogistics) : EMPTY_LOGISTICS);
    });
  }

  subscribeCriticalEvents(tripId: string, cb: (events: CriticalEvent[]) => void): Unsubscribe {
    return onSnapshot(this.criticalEventsRef(tripId), snapshot => {
      const events = snapshot.docs
        .map(d => d.data() as CriticalEvent)
        .sort((a, b) =>
          `${a.targetDate ?? ''}-${a.targetTimeStr}-${a.id}`.localeCompare(
            `${b.targetDate ?? ''}-${b.targetTimeStr}-${b.id}`,
          ),
        );
      cb(events);
    });
  }

  async upsertCriticalEvent(tripId: string, event: CriticalEvent): Promise<void> {
    await setDoc(doc(this.criticalEventsRef(tripId), event.id), event);
  }

  async deleteCriticalEvent(tripId: string, eventId: string): Promise<void> {
    await deleteDoc(doc(this.criticalEventsRef(tripId), eventId));
  }

  async updateLogistics(tripId: string, logistics: TripLogistics): Promise<void> {
    await setDoc(this.logisticsDocRef(tripId), logistics);
  }

  async addActivity(tripId: string, dayId: string, activity: ItineraryActivity): Promise<void> {
    const dayDocRef = doc(this.itineraryDaysRef(tripId), dayId);
    await runTransaction(this.db, async tx => {
      const snap = await tx.get(dayDocRef);
      if (!snap.exists()) return;
      const day = snap.data() as ItineraryDay;
      tx.update(dayDocRef, { activities: [...day.activities, activity] });
    });
  }

  async deleteActivity(tripId: string, dayId: string, activityId: string): Promise<void> {
    const dayDocRef = doc(this.itineraryDaysRef(tripId), dayId);
    await runTransaction(this.db, async tx => {
      const snap = await tx.get(dayDocRef);
      if (!snap.exists()) return;
      const day = snap.data() as ItineraryDay;
      tx.update(dayDocRef, {
        activities: day.activities.filter(activity => activity.id !== activityId),
      });
    });
  }

  async updateActivityPeople(
    tripId: string,
    dayId: string,
    activityId: string,
    people: string[],
  ): Promise<void> {
    const dayDocRef = doc(this.itineraryDaysRef(tripId), dayId);
    await runTransaction(this.db, async tx => {
      const snap = await tx.get(dayDocRef);
      if (!snap.exists()) return;
      const day = snap.data() as ItineraryDay;
      tx.update(dayDocRef, {
        activities: day.activities.map(activity =>
          activity.id === activityId ? { ...activity, people } : activity,
        ),
      });
    });
  }

  async addDay(tripId: string, day: ItineraryDay): Promise<void> {
    const collectionRef = this.itineraryDaysRef(tripId);
    const snapshot = await getDocs(collectionRef);
    const existing = snapshot.docs.map(d => d.data() as ItineraryDay);
    const merged = [...existing, day].sort((a, b) => a.date.localeCompare(b.date));
    const renumbered = merged.map((d, index) => ({ ...d, dayNumber: index + 1 }));

    const batch = writeBatch(this.db);
    renumbered.forEach(d => batch.set(doc(collectionRef, d.id), d));
    await batch.commit();
  }

  async addPendingPlace(tripId: string, place: PendingPlace): Promise<void> {
    await setDoc(doc(this.pendingPlacesRef(tripId), place.id), place);
  }

  async deletePendingPlace(tripId: string, placeId: string): Promise<void> {
    await deleteDoc(doc(this.pendingPlacesRef(tripId), placeId));
  }

  async approvePlace(tripId: string, placeId: string, targetDayId: string): Promise<void> {
    const pendingDocRef = doc(this.pendingPlacesRef(tripId), placeId);
    const placeSnap = await getDoc(pendingDocRef);
    if (!placeSnap.exists()) return;
    const place = placeSnap.data() as PendingPlace;

    const dayDocRef = doc(this.itineraryDaysRef(tripId), targetDayId);
    const daySnap = await getDoc(dayDocRef);
    if (!daySnap.exists()) return;
    const day = daySnap.data() as ItineraryDay;

    const newActivity: ItineraryActivity = {
      id: `act-${Date.now()}`,
      time: '02:00 PM', // Default/estimated time, matches InMemoryTripRepository behavior
      type: mapCategoryToActivityType(place.category),
      title: place.title,
      description: place.description,
      location: place.location,
      status: 'Aprobado',
      // PR5: no more global `friends` fixture to fall back to — leaves
      // people empty rather than inventing a default from a fixture that no
      // longer models real trip membership.
      people: place.people && place.people.length > 0 ? place.people : [],
    };

    const newPin: PinnedPoint = {
      id: `pin-${Date.now()}`,
      title: place.title,
      description: place.description,
      category: place.category,
      image: APPROVED_PLACE_PIN_IMAGE,
      coords: {
        x: 200 + Math.random() * 500,
        y: 200 + Math.random() * 300,
      },
    };

    const batch = writeBatch(this.db);
    batch.update(dayDocRef, { activities: [...day.activities, newActivity] });
    batch.set(doc(this.pinsRef(tripId), newPin.id), newPin);
    batch.delete(pendingDocRef);
    await batch.commit();
  }

  async addChatMessage(tripId: string, message: ChatMessage): Promise<void> {
    await setDoc(doc(this.chatRef(tripId), message.id), message);
  }
}
